CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"


AROUND_TOKEN_INDEX = -300
DEFAULT_AROUND_TOKEN = "<around>"
DEFAULT_AR_START_TOKEN = "<ar_start>"
DEFAULT_AR_END_TOKEN = "<ar_end>"


DEPTH_TOKEN_INDEX = -400
DEFAULT_DEPTH_TOKEN = "<depth>"
DEFAULT_DEP_START_TOKEN = "<dep_start>"
DEFAULT_DEP_END_TOKEN = "<dep_end>"
